# Generated by Django 4.2.5 on 2023-10-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField(default='')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('citations', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
