# Generated by Django 4.2.5 on 2023-11-02 02:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='citations',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
